<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaleFashion.Domain\MaleFashion.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cortex.Mediator" Version="3.1.2" />
    <PackageReference Include="Mapster" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
  </ItemGroup>

</Project>
